kind: pipeline
name: build

steps:

- name: build
  image: node:10-alpine
  group: build
  commands:
    - npm install
    - npm run build
    - npm run test

- name: code-analysis
    image: committed/drone-sonarqube-node
    settings:
      host:
        from_secret: sonar_host
      token:
        from_secret: sonar_token
      ver: 1.0
      timeout: 20
      sources: .
      level: DEBUG
      showProfiling: true
