kind: pipeline
name: build

steps:

- name: build
  image: node:latest
  group: build
  environment:
    SONAR_HOST_URL:
      from_secret: sonar_host_url
    SONAR_TOKEN:
      from_secret: sonar_token
  commands:
    - npm install
    - printenv
    - npm run sonarqube-scan

# - name: sonarqube-analysis
#   image: sonarsource/sonar-scanner-cli
#   environment:
#     SONAR_HOST_URL:
#       from_secret: sonar_host_url
#     SONAR_TOKEN:
#       from_secret: sonar_token
#   commands:
#     - sonar-scanner